services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: "pokerdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "aboba"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 3s
      timeout: 10s
  backend:
    build: .
    restart: always
    environment:
      DB_HOST: "db"
      DB_PASSWORD: "aboba"
      DB_USER: "postgres"
      DB_PORT: "5432"
      DB_NAME: "pokerdb"
      PORT: "12345"
    depends_on:
      db:
        condition: service_healthy
        restart: true
  web:
    image: nginx
    restart: always
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
      read_only: true
    # - ./resources/card_img:/data/card_img:ro
    - ./dist:/data/dist
    ports:
    - "8080:80"
    depends_on:
      backend:
        condition: service_started