services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "pokerdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "aboba"
    networks:
      - backend
  backend:
    build: .
    restart: always
    ports:
      - "12345:12345"
    environment:
      DB_HOST: "db"
      DB_PASSWORD: "aboba"
      DB_USER: "postgres"
      DB_PORT: "5432"
      DB_NAME: "pokerdb"
      PORT: "12345"
    networks:
      - backend
    depends_on:
      - db
  web:
    image: nginx
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
      read_only: true
    - ./resources/card_img:/data/card_img:ro
    ports:
    - "8080:80"
    networks:
    - backend
    depends_on:
    - backend
networks:
  backend:
    driver: bridge