openapi: "3.0.3"
info:
  title: Poker server
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /user/create:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [Name, Pass]
              properties:
                Name:
                  type: string
                Pass:
                  type: string
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PairToken"
        "409":
          description: The name is already exist
        "422":
          description: The name or the pass doesn't allow
  /user/auth:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [Name, Pass]
              properties:
                Name:
                  type: string
                Pass:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PairToken"
        "409":
          description: The name doesn't exist
        "422":
          description: The name or the pass don't allow
  /user/me:
    get:
      security:
        - BearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Token isn't valid
    delete:
      security:
        - BearerAuth: []
      responses:
        "200":
          description: OK
        "401":
          description: Token isn't valid
    # put:
    #   security:
    #     - BearerAuth: []
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: "#/components/schemas/User"
    #   responses:
    #     "200":
    #       description: OK
    #     "401":
    #       description: Token isn't valid
  /game/join:
    post:
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [Id, Stack]
              properties:
                Id:
                  type: integer
                  description: Set -1, if you want to create a new game
                Stack:
                  type: integer
      responses:
        "200":
          description: joining success
        "201":
          description: Game created
          content:
            application/json:
              schema:
                type: object
                required: [Id]
                properties:
                  Id:
                    type: integer
        "401":
          description: Token isn't valid
        "409":
          description: User is in another game
        "400":
          description: The game doesn't exist
  # /user/{Id}:
  #   get:
  #     responses:
  #       "200":
  #         description: OK
  #         content:
  #           application/json:
  #             schema:
  #               $ref: "#/components/schemas/User"
  #       "401":
  #         description: Token isn't valid
  #   delete:
  #     description: ONLY FOR ADMIN
  #     security:
  #       - BearerAuth: []
  #     responses:
  #       "200":
  #         description: OK
  #       "401":
  #         description: Token isn't valid
  #       "403":
  #         description: Not admin
  #   put:
  #     description: ONLY FOR ADMIN
  #     security:
  #       - BearerAuth: []
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "#/components/schemas/User"
  #     responses:
  #       "200":
  #         description: OK
  #       "401":
  #         description: Token isn't valid
  #       "403":
  #         description: Not admin
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    PairToken:
      type: object
      required: [AccessToken, RefreshToken]
      properties:
        AccessToken:
          type: string
        RefreshToken:
          type: string
    User:
      type: object
      required: [Id, Name, Role, Balance]
      properties:
        Id:
          type: integer
          description: Id with your request body will ignore
        Name:
          type: string
        Role:
          type: string
        Balance:
          type: integer
